spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: circuit-breaker-user-service
          uri: lb://CIRCUIT-BREAKER-USER-SERVICE
          predicates:
           - Path=/user-service/**
            
        - id: circuit-breaker-catalog-service
          uri: lb://CIRCUIT-BREAKER-CATALOG-SERVICE
          predicates:
            - Path=/api/v1/catalogs/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    